### ISSUE TITLE
Hello Sir Getting this error

### ISSUE THREAD

**Issue by 5mehulhelp5** [viraxpress/Frontend#1]
![image](https://github.com/user-attachments/assets/1733cf2d-1910-496b-91e2-651b77a912d1)
also you should add php 8.3 capabilities

**Comment by viraxpress** [comment]
Hi @5mehulhelp5 , Thank you for trying it out and reporting the issue. We will check and get back to you as soon as possible!

**Comment by 5mehulhelp5** [comment]
@viraxpress Thank you for this amazing work.

**Comment by viraxpress** [comment]
Hi @5mehulhelp5 , we have applied the fix and updated the repo with the latest README.md file. Could you please try a fresh installation with the latest version and let us know if that works for you?

**Comment by 5mehulhelp5** [comment]
@viraxpress Yes It's fixed the issue.
Thank you for amazing work
