### ISSUE TITLE
checkout error

### ISSUE THREAD

**Issue by 5mehulhelp5** [viraxpress/Frontend#3]
when we select this option in admin 
![image](https://github.com/user-attachments/assets/5e5d37f6-2255-4ee7-813a-dac196dd965a)

on the frontend i am getting this error.
![image](https://github.com/user-attachments/assets/5f5a118e-f8ed-4b0e-9c81-8b4b57cd00fc)

Please check and let me know

**Comment by viraxpress** [comment]
Hi @5mehulhelp5 , checkout steps are not yet compatible with the ViraXpress frontend and we are working to release this feature soon. Could you please try assigning the **Magento Luma** theme for the checkout and try again?
